# Generated by Django 5.0.3 on 2024-03-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drfapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobile',
            name='discount',
            field=models.BooleanField(null=True),
        ),
    ]
